### ISSUE TITLE
Visualisierung RVIZ

### ISSUE THREAD

**Issue by cndrw** [cndrw/multi-truck-scenario#3]
Hallo Bandik,
um dein unübersehbares verlangen nach der Programmierung zu stillen gebe ich dir eine Aufgabe.

Kannst du heraus finden welche Zahlen genau welche Farbe bei RVIZ repräsentieren also z.B. "rot" = -100.
Das kannst du gleich als enum in die map.cpp schreiben, wenn du das gemacht hast kannst du auch gleich in der function "s2_solution_callback" die -20 mit deinem enum für grün ersetzen (z.B. Colors::green).

Die Früchte deiner Arbeit kannst du auch gleich sehen wenn du nach dem bauen `ros2 launch multi_truck_scenario scenario_S2.launch.py` ausführst.

Viel Spaß! :3

**Comment by BandikNickel** [comment]
Hallo Conrad,
in der Tat macht es aktuell Spaß ein wenig zu programmieren!

Ich habe die Aufgabe bearbeitet (hoffentlich zu deiner Zufriedenheit ;)). Kommentare stehen bei dem Code.

Gruß
